#!/bin/bash

IP=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'`

EMULATOR=~/bin/android/emulator/emulator_real
$EMULATOR  -writable-system -dns-server "$IP,8.8.8.8,8.8.4.4" "$@"
